sudo: false

language: node_js

node_js:
  - "6"
  - "5"
  - "4"

cache:
  directories:
    - node_modules

before_install:
  - "test ! -d node_modules || npm prune"

install:
  - npm install --no-optional

# "build" is currently triggered by postinstall script
#before_script:
#  - npm run build

script: npm run -s ws -- lint
