language: node_js

node_js:
  - "9"
  - "8"

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn test # also builds

jobs:
  include:
    - stage: deploy
      script:
        # publish on tag
        - if [ -n "$TRAVIS_TAG" ]; then node node_modules/.bin/workspace-publish; fi
      node: "9"

env:
  global:
    # SAUCE_USERNAME
    - secure: i1hoBtH+QrnIlNqBl3nH66JMFAij7gSNQ/5Fse3BC1S3rxcMKX+DxE/aqjACACSDMfFZ1pcz3VUclcl1VMONQWzEJYRxzAz5Qx5vVtXdoIYgUff+8pzsARpV5r+ysHfMGitVpBhjrVwip+CVKxt+zmQ8HviiosYVS41qnmfZAgRkJj2k8xjfEod+KTxgrw1USp5L6sG7xiCdqEfw8cLtWKLpFgJbkSnJFJDdWU3aQ04Z/46P3FNszoRsfALyEdZI+79rvwhoBe3XmSEG4R9B5IKFqo/9C4oq9wIupfRs5tdvgDeXkzY9NhJIWqyh30uk9R2HhjkTjm35XBKHyKFOkESPxeWCve+Y5ghV/e0/VwXdhZkFrWxVkVrf5KgZ12T2jxfFbKtQA545flH/zhgvklq91C9EPRMZoXAGX7lf/y467D1n1LxfmiLkeCmKe/FNcwfSXy2j/56AClrsQqJtLkldE51D4vg8hxe7sSDKR4YXFwFJH2OnPF39pOUCakU6/73+gLpI4+/wqgUqLeT2qKbI6bytx5YP85+C1sLYB/e8ef10rVtDBBIqgS06rB07mPUNnnghsJqhLwAkapYoYjyKZxHPBRwaC9REUjrvQiju+csVoe0UpGPeNX1B380/1lFw6OgamP3V2Q4yUjx3gQRqRFr8aCaWQufb7dtxBc4=
    # SAUCE_ACCESS_KEY
    - secure: ZrKqgdVfDc6X5sXhDv7rQqya/6uMCWZ63TGAPeyeHaWi19dGEIx1s5LI7s4uXEWzV3fKQQlyWxF+m0UziNnqscouUjqHLwHkoTFPdSXzSXS9h6uy2f/BUxEUIAyCHdWrrrstIk5e0ODj2AdLEKnb7S+Fz7fG2iq1+6uv7ArNXMkX0d/xguKN71MBAs3OFJSv1Licy0ixfOBL/kdW06uKl5w548DJfErxyhrcX4pFbp6b5qo9l1kOtTX/QNLTLf6Nn4dcgM2pUJqmJBc009SZbsrE1D5uHq+kFOjBw78MUF2w27+ywftL526/+2i9mk6vjaq8mgG8kT8DZvnSrufM1j/o5ZNlOAGwfWGHlcin8TmhPW01rBcJapY6YO9cd6nI3IS9ClQxyK52khQuydfVpIFi96gq7ZlljqoPxV3mEftOfTG1INAVVUCcMhGAHxvoLO0l40E/FxfZeReDg5GFBCnSfi0eLQ4n4MDIT80fc/TZtOFTRqHzbbJ3369afZbUd0wzss+b6PmzRulMvr31Wc5daEWuEyCSsLm/mnKfJ4OZsAW6muSGQuPk6y/Vrgouxgpur7ofcORamRZlcA9KaFM5LNqIgYBvRr9pqKPZYkMsQb7B4n4JXOHZ2OVJUwFrXM/pOloUZSMmZVUaKvn/33PtGvWDHtQTcFB+iXrhnMo=
    # NPM_TOKEN
    - secure: qbXmWg0FzwPat9ikYm9uM3NJCG42Qqu1U2anVwsw3MEzk/9DSAkAl8htxJQqn5AaG5mUk9N7nUS/ZSJX6wGz8yOe9YeXyRQTePcJnuX3/sTKgBGjkpVP9tGAu/jQMykODEhq9jRpvE9f03j3zNP+kZTJk7uxWq8AGAxV12bwOFvHLMoY1PNkediRcezRga3T14JXrKtGHWKU3xUNI84Ok2P1b6M+19TTOsIvcPRoDrrRx9l3EdCluYIEJG/G8qxNX69NRRNbBwSbtR8YZtuhZ/wtUhKw6W8opmuE+dxwIJxvkDSHr+FyVPgOlu/2T3c6JUEW36hVQVSs6wUYBpfIgHa+R6HkaBlUqYkLoPB8OagHCZhj4RTYZIxGXV3taOt1yLWG/nQFszYfwTYKAPIUQJz02nRMUcRBzQTKK0HZvO1zBdEQ68wN4aYVSZEOa96gEsky8Hi30+z9OfdJkZz3LsK7P45gmJ5/3xyIw58Nm1nZkrRutZ0KULTmUoD6U+VFgOEYonvlvtmFhabscj1ZwPjMcy7/oR2K0dRVRd+ueAFN0RGf/mCCLg2/+JW/4aP9aMmkUL8PAvEJyikndZ1H2hr3jYivQ3xexzOsYPE+Qd0OIet6Q0R9MeAX4uaFklUn3pQuFuj3Fp0aj+odXEIWTGem04ujMm6nT/pm3cbfCwk=
