sudo: false

language: node_js

node_js:
  - "6"
  - "5"
  - "4"

cache:
  directories:
    - node_modules

before_install:
  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"

before_script:
  - npm run build

script: npm run -s ws -- lint
