sudo: false

language: node_js

node_js:
  - "7"
  - "6"

cache:
  yarn: true
  directories:
    - node_modules

#install:
#  - npm install --no-optional

before_script:
  - npm run build

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - test ! -d node_modules || npm prune

script:
  - npm run -s ws lint
  - node scripts/update-examples.js

after_script:
  - "sh -e /etc/init.d/xvfb stop"

env:
  global:
    # secure SAUCE_USERNAME
    - secure: >-
        i1hoBtH+QrnIlNqBl3nH66JMFAij7gSNQ/5Fse3BC1S3rxcMKX+DxE/aqjACACSDMfFZ1pcz3VUclcl1VMONQWzEJYRxzAz5Qx5vVtXdoIYgUff+8pzsARpV5r+ysHfMGitVpBhjrVwip+CVKxt+zmQ8HviiosYVS41qnmfZAgRkJj2k8xjfEod+KTxgrw1USp5L6sG7xiCdqEfw8cLtWKLpFgJbkSnJFJDdWU3aQ04Z/46P3FNszoRsfALyEdZI+79rvwhoBe3XmSEG4R9B5IKFqo/9C4oq9wIupfRs5tdvgDeXkzY9NhJIWqyh30uk9R2HhjkTjm35XBKHyKFOkESPxeWCve+Y5ghV/e0/VwXdhZkFrWxVkVrf5KgZ12T2jxfFbKtQA545flH/zhgvklq91C9EPRMZoXAGX7lf/y467D1n1LxfmiLkeCmKe/FNcwfSXy2j/56AClrsQqJtLkldE51D4vg8hxe7sSDKR4YXFwFJH2OnPF39pOUCakU6/73+gLpI4+/wqgUqLeT2qKbI6bytx5YP85+C1sLYB/e8ef10rVtDBBIqgS06rB07mPUNnnghsJqhLwAkapYoYjyKZxHPBRwaC9REUjrvQiju+csVoe0UpGPeNX1B380/1lFw6OgamP3V2Q4yUjx3gQRqRFr8aCaWQufb7dtxBc4=
    # secure SAUCE_ACCESS_KEY
    - secure: >-
        ZrKqgdVfDc6X5sXhDv7rQqya/6uMCWZ63TGAPeyeHaWi19dGEIx1s5LI7s4uXEWzV3fKQQlyWxF+m0UziNnqscouUjqHLwHkoTFPdSXzSXS9h6uy2f/BUxEUIAyCHdWrrrstIk5e0ODj2AdLEKnb7S+Fz7fG2iq1+6uv7ArNXMkX0d/xguKN71MBAs3OFJSv1Licy0ixfOBL/kdW06uKl5w548DJfErxyhrcX4pFbp6b5qo9l1kOtTX/QNLTLf6Nn4dcgM2pUJqmJBc009SZbsrE1D5uHq+kFOjBw78MUF2w27+ywftL526/+2i9mk6vjaq8mgG8kT8DZvnSrufM1j/o5ZNlOAGwfWGHlcin8TmhPW01rBcJapY6YO9cd6nI3IS9ClQxyK52khQuydfVpIFi96gq7ZlljqoPxV3mEftOfTG1INAVVUCcMhGAHxvoLO0l40E/FxfZeReDg5GFBCnSfi0eLQ4n4MDIT80fc/TZtOFTRqHzbbJ3369afZbUd0wzss+b6PmzRulMvr31Wc5daEWuEyCSsLm/mnKfJ4OZsAW6muSGQuPk6y/Vrgouxgpur7ofcORamRZlcA9KaFM5LNqIgYBvRr9pqKPZYkMsQb7B4n4JXOHZ2OVJUwFrXM/pOloUZSMmZVUaKvn/33PtGvWDHtQTcFB+iXrhnMo=
