sudo: false

language: node_js

node_js:
  - "6"
#  - "5"
#  - "4"

cache:
  directories:
    - node_modules

before_install:
  - test ! -d node_modules || npm prune
#  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

install:
  - npm install --no-optional

# build is triggered by prepublish hook which is triggered by npm install
#before_script:
#  - npm run build

script:
  - npm run -s ws lint
  - node scripts/update-examples.js
